/**
 * SYNTHETIC DATA — Contract Change Intelligence Engine (Wave 3).
 * The change set mirrors the demo negotiation: AusCare's 1 Aug reply expressed
 * as tracked contractual changes, plus hospital-originated proposals. In
 * production every item is generated by diffing draft versions and enriched
 * with impact/valuation analysis.
 */

export type Originator = 'Health fund' | 'Hospital'
export type Favour = 'Favourable to hospital' | 'Favourable to fund' | 'Neutral'
export type ChangeStatus = 'Open' | 'Countered' | 'Agreed in principle' | 'Rejected' | 'Parked'

export interface ChangeItem {
  id: string
  originator: Originator
  clauseRef: string
  title: string
  currentText: string
  proposedText: string
  favour: Favour
  risk: 'High' | 'Medium' | 'Low'
  priority: number // 1-10
  annualValue: number // + to hospital, − against
  status: ChangeStatus
  owner: string
  impacts: { commercial: string; operational: string; implementation: string }
  summary: string
  action: string
  history: { when: string; what: string }[]
}

export const changes: ChangeItem[] = [
  {
    id: 'CH-1', originator: 'Health fund', clauseRef: 'Schedule 1', title: 'Rates: +2.5% across all bands',
    currentText: 'Year-3 rates per Schedule 1 (post FY25/FY26 indexation events).',
    proposedText: 'All Band rates increased 2.5% from 1 December 2026.',
    favour: 'Favourable to fund', risk: 'Medium', priority: 8, annualValue: -95_000,
    status: 'Countered', owner: 'CEO',
    impacts: {
      commercial: 'Anchors ~1.5 points below the walk-away minimum on cataract; locks the FY26 re-banding losses in.',
      operational: 'None directly.',
      implementation: 'Schedule reload only.',
    },
    summary: 'A below-target opening anchor dressed as generosity ("above our standard settlement range"). Accepting forfeits ~$95k/yr against the modelled target package.',
    action: 'Counter tabled 8 Aug: cataract +6.5% with evidence pack; colonoscopy +4%; arthroscopy +5.5%; Band 4 accepted at +2.5%.',
    history: [
      { when: '1 Aug 2026', what: 'Proposed by AusCare in written response.' },
      { when: '8 Aug 2026', what: 'Countered with Annexure A episode-level analysis.' },
    ],
  },
  {
    id: 'CH-2', originator: 'Health fund', clauseRef: 'cl. 12.3', title: 'Replace carve-out with "50% of CPI floor"',
    currentText: 'Fund may apply a lower Indexation Amount (including zero) in its discretion…',
    proposedText: '"…the Fund will apply an amount no less than 50% of the Indexation Amount and will consult with the Hospital before doing so."',
    favour: 'Favourable to fund', risk: 'High', priority: 10, annualValue: -22_000,
    status: 'Countered', owner: 'CEO',
    impacts: {
      commercial: 'Converts a contestable discretion into a contractual right to under-index. Expected cost vs full CPI ≈ $22k/yr on historical exercise patterns.',
      operational: 'Budget uncertainty persists.',
      implementation: 'None.',
    },
    summary: 'The letter’s sharpest trap: reads as a concession ("a floor!") while legalising half-CPI indexation. Worse than the current clause, which at least must survive a reasonableness argument.',
    action: 'Reject the wording; accept the shape: a floor set at 100% of the Indexation Amount, with cl. 12.3 deleted. Non-negotiable for a multi-year term.',
    history: [
      { when: '1 Aug 2026', what: 'Proposed by AusCare as "acknowledging your preference for certainty".' },
      { when: '8 Aug 2026', what: 'Rejected with counter: clauses 12.1–12.2 unchanged, 12.3 deleted.' },
    ],
  },
  {
    id: 'CH-3', originator: 'Health fund', clauseRef: 'cl. 8.4', title: 'Re-banding referred to fund’s internal committee',
    currentText: 'Fund may reassign bands unilaterally on 30 days’ notice.',
    proposedText: 'Future classification questions referred to the Fund’s Clinical Classification Committee.',
    favour: 'Favourable to fund', risk: 'High', priority: 9, annualValue: 0,
    status: 'Countered', owner: 'CEO',
    impacts: {
      commercial: 'Cosmetic: the "referee" is a committee of fund employees; unilateral power survives with better PR. FY26 re-bandings stay unremedied.',
      operational: 'Adds a submission process without adding rights.',
      implementation: 'None.',
    },
    summary: 'Accepting would ratify cl. 8.4 while appearing to reform it — and would surrender the strongest evidence-based ask in the package.',
    action: 'Counter: committee acceptable as first instance only; unresolved matters to a jointly-appointed independent coding expert, binding. FY26 re-bandings restored.',
    history: [
      { when: '1 Aug 2026', what: 'Proposed by AusCare ("determinations by appropriately qualified staff").' },
      { when: '8 Aug 2026', what: 'Countered with two-tier referee model.' },
    ],
  },
  {
    id: 'CH-4', originator: 'Health fund', clauseRef: 'Schedule 4 (new)', title: 'Provider Digital Compliance schedule',
    currentText: '— (no equivalent schedule)',
    proposedText: 'New Schedule 4: digital claiming, portal usage, data standards and system-compliance obligations "as updated by the Fund from time to time".',
    favour: 'Favourable to fund', risk: 'Medium', priority: 7, annualValue: -18_000,
    status: 'Parked', owner: 'Finance Manager',
    impacts: {
      commercial: 'Unpriced, open-ended compliance obligation with unilateral update right.',
      operational: 'Unknown until reviewed — likely portal workflow + reporting changes.',
      implementation: 'Potential PMS configuration and staff training cost (est. $18k/yr equivalent).',
    },
    summary: 'A new obligation introduced mid-negotiation, sight-unseen, with an "as updated" ratchet. Never accept unpriced schedules inside a rates negotiation.',
    action: 'Quarantined to a separate workstream: 20-business-day review after the schedule is provided; any cost priced and passed through or offset.',
    history: [
      { when: '1 Aug 2026', what: 'Introduced by AusCare, copy "enclosed".' },
      { when: '8 Aug 2026', what: 'Parked by agreement pending review window.' },
    ],
  },
  {
    id: 'CH-5', originator: 'Hospital', clauseRef: 'cl. 14.2', title: 'Contractual 14-day claims lodgement',
    currentText: 'Claims must be lodged within 30 days of discharge.',
    proposedText: 'Hospital commits to lodgement within 14 days (internal standard 7 days retained).',
    favour: 'Neutral', risk: 'Low', priority: 4, annualValue: 0,
    status: 'Agreed in principle', owner: 'Finance Manager',
    impacts: {
      commercial: 'Costless give — the internal 7-day standard already outperforms it. Improves the fund’s cash-flow forecasting.',
      operational: 'None (buffer halves but stays real).',
      implementation: 'None.',
    },
    summary: 'Deliberate trade currency: something the fund values that costs Bayview nothing.',
    action: 'Accepted by AusCare 1 Aug. Bank it and reference it when holding the line on cl. 14.5.',
    history: [
      { when: '6 Jul 2026', what: 'Offered in Bayview opening letter.' },
      { when: '1 Aug 2026', what: 'Accepted by AusCare.' },
    ],
  },
  {
    id: 'CH-6', originator: 'Hospital', clauseRef: 'cl. 17.3 (new 17.4)', title: 'Quality incentive loading (+0.5%)',
    currentText: 'No payment, bonus, or rate adjustment attaches to favourable KPI performance.',
    proposedText: 'New cl. 17.4: sustained top-quartile Schedule 3 performance over four consecutive quarters entitles the Hospital to a 0.5% loading on the next indexation event.',
    favour: 'Favourable to hospital', risk: 'Low', priority: 6, annualValue: 15_000,
    status: 'Open', owner: 'CEO',
    impacts: {
      commercial: '+$15.6k/yr at current base; aligns quality with revenue.',
      operational: 'Uses the existing quarterly KPI pack — zero added burden.',
      implementation: 'Loading calculation at indexation events.',
    },
    summary: 'Hospital-proposed clause built on the Federation cl. 7.1 template and 8 quarters of Bayview\'s own data. The AI-drafted wording, rationale and objection handling are in the proposal pack.',
    action: 'Tabled 8 Aug. Expected objection: "no precedent in our portfolio" — response: Federation precedent + the fund\'s own public quality narrative.',
    history: [{ when: '8 Aug 2026', what: 'Proposed by Bayview with drafted clause + evidence pack.' }],
  },
  {
    id: 'CH-7', originator: 'Hospital', clauseRef: 'cl. 2.2', title: 'Indexed holdover',
    currentText: 'No indexation applies during any holdover period.',
    proposedText: 'Rates during holdover are indexed per cl. 12 as if the Agreement had renewed.',
    favour: 'Favourable to hospital', risk: 'Low', priority: 8, annualValue: 30_000,
    status: 'Open', owner: 'CEO',
    impacts: {
      commercial: 'Removes the fund’s delay incentive (~$10k/month currently).',
      operational: 'None.',
      implementation: 'None.',
    },
    summary: 'The quick win that protects every other lever: once delay is cost-neutral, the calendar stops negotiating for the fund.',
    action: 'Asked in both letters; fund silent — restate at 19 Aug meeting as a good-faith test.',
    history: [
      { when: '6 Jul 2026', what: 'Proposed in opening letter.' },
      { when: '8 Aug 2026', what: 'Restated in counter; response pending.' },
    ],
  },
]

// -------------------------------------------- hospital-proposed clause (CH-6)
export const proposedClause = {
  id: 'CH-6',
  title: 'Quality incentive loading — proposal pack',
  draftWording:
    '17.4  Where the Hospital achieves performance at or better than the top quartile of the Schedule 3 benchmarks for four consecutive Quarters, the rates in Schedule 1 will be increased by an additional 0.5% at the next indexation event ("Quality Loading"). The Quality Loading applies for the following 12 months and renews on the same test. Determination is by reference to the quarterly reports already provided under clause 17.2, with any dispute resolved under clause 18.',
  rationale:
    'Quality currently carries only downside under this Agreement (cl. 17.3 makes adverse variance a breach trigger while attaching nothing to excellence). Bayview has delivered top-quartile results for eight consecutive quarters — performance the Fund already markets to members. A 0.5% loading converts a proven member benefit into a priced term, using reporting that already exists, at a cost of ~$15.6k/yr against a $3.1m base.',
  financialImpact: '+$15.6k/yr at current volumes; self-funding for the Fund if it retains even ~7 members/yr through reduced complaints and waits.',
  implementation: 'No new reporting. Loading computed at indexation events from existing cl. 17.2 quarterly packs.',
  objections: [
    { objection: '"No precedent in our provider portfolio."', response: 'Federation Health has paid the identical structure since FY26 (cl. 7.1). Precedent exists in this facility\'s own portfolio.' },
    { objection: '"Quality is an accreditation baseline, not a payable."', response: 'Agreed for the baseline — this pays only sustained top-quartile performance, the tier your member materials advertise.' },
    { objection: '"Creates cost uncertainty."', response: 'Capped by construction at 0.5% of one facility\'s base; fully forecastable from quarterly data the Fund already receives.' },
  ],
  alternatives: [
    'Alternative A (softer): loading banked as a credit against any future cl. 15 audit cost-shifting.',
    'Alternative B (staged): 0.25% year 1, 0.5% thereafter on the same test.',
  ],
  strategy: 'Introduce after the re-banding evidence lands (round 2) as the constructive counterweight — it lets the fund say yes to something.',
}

// ------------------------------------------------------ scenario modelling
export interface Scenario {
  name: string
  likelihoodPct: number
  commercial: string
  financial: string
  next: string
}

export const scenariosFor: Record<string, Scenario[]> = {
  'CH-2': [
    { name: 'Fund accepts deletion', likelihoodPct: 30, commercial: 'Carve-out gone; indexation integrity restored.', financial: '+$45k/yr expected value.', next: 'Bank it; close rates within one round.' },
    { name: 'Fund partially accepts', likelihoodPct: 40, commercial: 'Floor at 100% of CPI, carve-out survives in name for "exceptional circumstances" with tight definition.', financial: '+$38k/yr expected value.', next: 'Acceptable if "exceptional" is defined and disputable; get worked examples into the drafting.' },
    { name: 'Fund holds 50% floor', likelihoodPct: 20, commercial: 'Under-indexation legalised.', financial: '−$22k/yr vs current expected value.', next: 'Refuse multi-year term; offer 18-month term at CPI as the alternative package.' },
    { name: 'Fund counters with new mechanism', likelihoodPct: 10, commercial: 'E.g. indexation linked to premium-round outcome.', financial: 'Model on receipt — premium rounds have run above paid indexation for 5 years.', next: 'Potentially attractive; verify against the 5-year premium series before responding.' },
  ],
  'CH-6': [
    { name: 'Fund accepts', likelihoodPct: 25, commercial: 'Quality priced; precedent set for renewals.', financial: '+$15.6k/yr.', next: 'Offer joint case-study rights as the sweetener.' },
    { name: 'Fund partially accepts', likelihoodPct: 35, commercial: 'Staged loading (Alt B) or credit model (Alt A).', financial: '+$8–12k/yr.', next: 'Take Alt B; lock the full rate at year 2.' },
    { name: 'Fund rejects', likelihoodPct: 30, commercial: 'Quality stays unpaid on this agreement.', financial: '$0.', next: 'Park; convert to a year-1 review clause so the door stays open.' },
    { name: 'Fund counters with conditions', likelihoodPct: 10, commercial: 'E.g. loading tied to No-Gap participation.', financial: 'Model the No-Gap economics first.', next: 'Treat as a separate commercial negotiation — do not bundle blind.' },
  ],
}
