/**
 * SYNTHETIC DATA — Contract Clause Intelligence Engine (Wave 1).
 * Typed data contracts: in production these records are generated by the
 * model from uploaded contracts + PAS/financial data; here they are authored
 * fixtures over the two synthetic HPPAs. Every valuation carries method,
 * confidence and provenance; human overrides append to an audit trail.
 */

export type Contract = 'AusCare' | 'Federation'

export type ClauseCategory =
  | 'Commercial' | 'Financial' | 'Operational' | 'Compliance' | 'Reporting'
  | 'Clinical' | 'Audit' | 'Legal' | 'Quality' | 'Data sharing' | 'Payment'
  | 'Termination' | 'Governance' | 'Risk allocation'

export type Risk = 'High' | 'Medium' | 'Low'

export interface ValuationOverride {
  when: string
  by: string
  from: number
  to: number
  rationale: string
}

export interface Valuation {
  method: 'Automated (PAS + revenue data)' | 'Rules-based estimate' | 'Manual (commercial judgement)'
  annualValue: number      // $ p.a. exposure or opportunity
  negotiationValue?: number
  confidence: 'High' | 'Medium' | 'Low'
  basis: string            // provenance / rationale
  overrides: ValuationOverride[]
}

export interface ClauseRecord {
  id: string
  contract: Contract
  ref: string
  title: string
  category: ClauseCategory
  excerpt: string
  plain: string
  commercialImpact: string
  operationalImpact: string
  burden: 1 | 2 | 3 | 4 | 5
  complexity: 1 | 2 | 3 | 4 | 5
  risk: Risk
  unfair?: { type: string; reasons: string[] }
  negotiationPriority: number // 1–10
  valuation?: Valuation
  evidence: string[]
}

export const clauses: ClauseRecord[] = [
  // ---------------- AusCare (2023) — the adverse contract ----------------
  {
    id: 'AC-12.3', contract: 'AusCare', ref: 'cl. 12.3', title: 'Discretionary indexation carve-out',
    category: 'Financial',
    excerpt: '…the Fund may, by notice before an anniversary, apply a lower Indexation Amount (including zero) where the Fund determines, in its discretion…',
    plain: 'AusCare can pay less than CPI — down to zero — whenever it decides its own affordability requires it. It only owes you a written summary of why.',
    commercialImpact: 'Converts contracted indexation into a fund option. Exercised FY25: 1.9% paid vs 3.4% CPI; base permanently lowered.',
    operationalImpact: 'Budgeting uncertainty every anniversary; no reliable revenue forecast.',
    burden: 2, complexity: 2, risk: 'High',
    unfair: { type: 'Unilateral variation right', reasons: ['One-sided discretion over a core price term', '"Acting reasonably" is undefined and untested', 'No symmetrical hospital right'] },
    negotiationPriority: 10,
    valuation: {
      method: 'Automated (PAS + revenue data)', annualValue: 45_000, negotiationValue: 45_000,
      confidence: 'High',
      basis: 'FY25 exercise measured from remittances: 1.5pt shortfall × $3.0m AusCare base = $45k/yr, compounding into every later year.',
      overrides: [],
    },
    evidence: ['FY25 indexation notice (1.9%)', 'ABS CPI Jun-25 (3.4%)', 'Remittance reconciliation FY25–26'],
  },
  {
    id: 'AC-8.4', contract: 'AusCare', ref: 'cl. 8.4', title: 'Unilateral re-banding right',
    category: 'Commercial',
    excerpt: '…the Fund may reassign any Recognised Procedure to a different Band by giving the Hospital 30 days’ written notice… does not require the Hospital’s consent.',
    plain: 'AusCare can move any procedure to a lower-paying band with a month\'s notice. You cannot refuse — only complain.',
    commercialImpact: 'A quiet rate cut. Exercised twice FY26: four ophthalmic item groups moved Band 2 → 1.',
    operationalImpact: 'Booking/billing reconfiguration at 30 days; CEO escalation workflow required (DR-2025-02).',
    burden: 3, complexity: 3, risk: 'High',
    unfair: { type: 'Unilateral variation right', reasons: ['Price-affecting reclassification without consent', 'No independent referee', 'Asymmetric: hospital requests take 90 business days (cl. 8.3)'] },
    negotiationPriority: 10,
    valuation: {
      method: 'Automated (PAS + revenue data)', annualValue: 108_000, negotiationValue: 108_000,
      confidence: 'Medium',
      basis: 'FY26 re-bandings: ~210 episodes × $1,127 band differential, offset for case-mix substitution (midpoint of $95–120k).',
      overrides: [],
    },
    evidence: ['Re-banding notices Feb & May 2026', 'Episode-level billing FY26', 'Schedule 1 band differentials'],
  },
  {
    id: 'AC-14.5', contract: 'AusCare', ref: 'cl. 14.5', title: '24-month set-off & recovery',
    category: 'Payment',
    excerpt: '…the Fund may recover the overpayment at any time within 24 months of payment, including by set-off against any amount otherwise payable…',
    plain: 'For two years after paying a claim, AusCare can decide it overpaid and simply deduct the money from your next remittance.',
    commercialImpact: 'Open look-back on ~$3.1m of annual receipts; audits can convert directly to clawback.',
    operationalImpact: 'Reconciliation burden; every set-off must be detected, verified and disputed within 20 business days.',
    burden: 4, complexity: 3, risk: 'High',
    unfair: { type: 'Recovery provision', reasons: ['24 months vs your 30-day lodgement bar — a 24:1 asymmetry', 'Set-off without prior dispute resolution', 'Disputed amounts not excluded'] },
    negotiationPriority: 8,
    valuation: {
      method: 'Rules-based estimate', annualValue: 32_000, negotiationValue: 24_000,
      confidence: 'Medium',
      basis: 'Exposure proxy: audit-season at-risk value (FY26 $48.6k challenged) × historical concession rate (~35%) + reconciliation labour (~0.1 FTE).',
      overrides: [],
    },
    evidence: ['RI dashboard FY26 outcomes', 'Audit history 24 months', 'Finance time-tracking'],
  },
  {
    id: 'AC-14.2', contract: 'AusCare', ref: 'cl. 14.2', title: '30-day claim lodgement bar',
    category: 'Payment',
    excerpt: 'A claim must be lodged within 30 days of the date of discharge. The Fund may reject a claim lodged after that period…',
    plain: 'Miss the 30-day window and the claim is gone — and you are barred from billing the patient instead.',
    commercialImpact: 'Hard revenue forfeiture. $4.1k written off FY25 before the internal 7-day standard.',
    operationalImpact: 'Drives the whole-of-facility 7-day lodgement rule; lab-report delays create structural risk.',
    burden: 3, complexity: 1, risk: 'Medium',
    unfair: { type: 'Short notice period', reasons: ['Half the Federation window with no reasonable-delay carve-out', 'Combined with cl. 14.5 the asymmetry is 24 months vs 30 days'] },
    negotiationPriority: 6,
    valuation: {
      method: 'Automated (PAS + revenue data)', annualValue: 6_000,
      confidence: 'High',
      basis: 'FY25 write-offs annualised + residual near-miss rate from lodgement-lag distribution in the PAS.',
      overrides: [],
    },
    evidence: ['FY25 write-off register', 'Lodgement-lag distribution (PAS)'],
  },
  {
    id: 'AC-2.2', contract: 'AusCare', ref: 'cl. 2.2', title: 'Frozen holdover',
    category: 'Commercial',
    excerpt: '…this Agreement continues on a month-to-month basis on the rates current at expiry, and no indexation applies during any holdover period.',
    plain: 'If renewal talks run past expiry, your rates freeze. Every month of delay costs you and costs AusCare nothing.',
    commercialImpact: 'Hands the fund the calendar as a weapon: ~$8–11k forgone indexation per month of drift.',
    operationalImpact: 'Forces negotiation urgency onto the hospital side only.',
    burden: 1, complexity: 1, risk: 'High',
    unfair: { type: 'One-sided obligation', reasons: ['Delay is free for one party and costly for the other', 'Federation equivalent indexes the holdover'] },
    negotiationPriority: 9,
    valuation: {
      method: 'Rules-based estimate', annualValue: 30_000, negotiationValue: 20_000,
      confidence: 'Medium',
      basis: '3-month expected drift (sector norm for contested renewals) × ~$10k/month forgone indexation.',
      overrides: [],
    },
    evidence: ['Federation cl. 2.2 (indexed holdover) as market comparator'],
  },
  {
    id: 'AC-10.2', contract: 'AusCare', ref: 'cl. 10.2', title: 'IOL bundled into cataract rate',
    category: 'Financial',
    excerpt: '…the Case Payment is inclusive of the intraocular lens and all associated consumables… regardless of the lens selected.',
    plain: 'The lens comes out of your case payment, whatever it costs. Lens price inflation is your problem, not the fund\'s.',
    commercialImpact: 'Real cataract rate erodes ~2.1% since 2023 through lens cost drift; premium-lens handling pushed onto IFC.',
    operationalImpact: 'Consignment tracking + IFC workflow (DR-2024-07) to avoid absorbing upgrade costs.',
    burden: 3, complexity: 2, risk: 'Medium',
    unfair: { type: 'Risk allocation', reasons: ['Input-cost risk transferred without an adjustment mechanism', 'Federation pays prostheses separately at the Prescribed List'] },
    negotiationPriority: 7,
    valuation: {
      method: 'Automated (PAS + revenue data)', annualValue: 27_000,
      confidence: 'Medium',
      basis: '640 AusCare cataract episodes × measured lens-cost drift vs 2023 baseline.',
      overrides: [],
    },
    evidence: ['Consignment invoices 2023–26', 'Prescribed List benefit movements'],
  },
  {
    id: 'AC-19.1', contract: 'AusCare', ref: 'cl. 19.1', title: 'Asymmetric termination (90/180 days)',
    category: 'Termination',
    excerpt: 'The Fund may terminate… 90 days’ written notice. The Hospital may terminate… 180 days’ written notice.',
    plain: 'AusCare can leave in three months; you must give six. They can credibly threaten exit twice as fast as you can.',
    commercialImpact: 'Weakens every other negotiation position; planning horizon set by the shorter fund-side notice.',
    operationalImpact: 'Contingency planning must assume 90-day revenue cliff.',
    burden: 1, complexity: 1, risk: 'Medium',
    unfair: { type: 'One-sided obligation', reasons: ['2:1 notice asymmetry with no justification', 'Federation is symmetric at 60 days'] },
    negotiationPriority: 7,
    valuation: {
      method: 'Manual (commercial judgement)', annualValue: 0, negotiationValue: 15_000,
      confidence: 'Low',
      basis: 'No direct cash flow; valued as negotiation-leverage correction (risk-adjusted option value assigned by CEO).',
      overrides: [{ when: 'Jul 2026', by: 'CEO', from: 0, to: 15_000, rationale: 'Symmetry is a cheap give for the fund and materially improves our BATNA credibility — worth holding in the package.' }],
    },
    evidence: ['Federation cl. 8.1 comparator'],
  },
  {
    id: 'AC-17.3', contract: 'AusCare', ref: 'cl. 17.3', title: 'KPI obligations with no upside',
    category: 'Quality',
    excerpt: '…persistent adverse variance… is a material breach… No payment, bonus, or rate adjustment attaches to favourable KPI performance.',
    plain: 'Bad quality numbers can end your contract; excellent ones earn you nothing.',
    commercialImpact: 'Quality is all downside. Bayview outperforms every Schedule 3 benchmark and captures zero value.',
    operationalImpact: 'Quarterly reporting effort with no commercial return.',
    burden: 2, complexity: 1, risk: 'Medium',
    unfair: { type: 'Penalty asymmetry', reasons: ['Breach trigger with no matching incentive', 'Federation pays a 0.5% quality loading for the same performance'] },
    negotiationPriority: 6,
    valuation: {
      method: 'Rules-based estimate', annualValue: 15_000, negotiationValue: 15_000,
      confidence: 'Medium',
      basis: 'A Federation-style 0.5% loading on the AusCare base ($3.1m) = $15.6k/yr — the value currently left on the table.',
      overrides: [],
    },
    evidence: ['Schedule 3 KPI results (8 consecutive quarters top-quartile)', 'Federation cl. 7.1 comparator'],
  },
  {
    id: 'AC-15.2', contract: 'AusCare', ref: 'cl. 15.2', title: 'Audit costs shift at 2% threshold',
    category: 'Audit',
    excerpt: '…Where an audit identifies a net overpayment exceeding 2% of the audited sample value, the Hospital must also pay the Fund’s reasonable audit costs.',
    plain: 'If an audit finds errors above a low bar, you pay for the fund\'s audit as well as the clawback.',
    commercialImpact: 'Amplifies audit downside; 2% of a sample is a handful of coding queries.',
    operationalImpact: 'Raises stakes of every audit response; drives defensive documentation cost.',
    burden: 2, complexity: 2, risk: 'Medium',
    unfair: { type: 'Excessive audit power', reasons: ['Cost-shifting threshold set at trivial error rate', 'No matching hospital right when audits find underpayment'] },
    negotiationPriority: 5,
    valuation: {
      method: 'Rules-based estimate', annualValue: 8_000,
      confidence: 'Low',
      basis: 'Probability-weighted: 2 audits/yr × ~20% breach-of-threshold likelihood × ~$20k typical audit cost.',
      overrides: [],
    },
    evidence: ['FY26 audit outcomes (0 threshold breaches — defensive cost already sunk)'],
  },
  {
    id: 'AC-16.2', contract: 'AusCare', ref: 'cl. 16.2', title: 'Broad fund use of hospital data',
    category: 'Data sharing',
    excerpt: 'Data provided under this clause may be used by the Fund for benchmarking, contracting, and portfolio analysis.',
    plain: 'Your monthly casemix data feeds the fund\'s negotiation database — including the one used against you.',
    commercialImpact: 'Information asymmetry codified: your data improves their benchmarks.',
    operationalImpact: 'Monthly HCP + utilisation reporting.',
    burden: 2, complexity: 1, risk: 'Medium',
    unfair: { type: 'One-sided obligation', reasons: ['No reciprocal data flow to the hospital', 'Use extends beyond claims administration to "contracting"'] },
    negotiationPriority: 4,
    valuation: {
      method: 'Manual (commercial judgement)', annualValue: 0, negotiationValue: 8_000,
      confidence: 'Low',
      basis: 'Strategic value only; CEO holds as a tradeable ask (purpose limitation) rather than a cash item.',
      overrides: [],
    },
    evidence: ['cl. 16.1–16.2 text'],
  },
  {
    id: 'AC-20.1', contract: 'AusCare', ref: 'cl. 20.1', title: 'Rate confidentiality',
    category: 'Legal',
    excerpt: 'The Hospital must not disclose the rates in Schedule 1 to any other hospital or day procedure centre…',
    plain: 'Standard confidentiality — and also the clause that keeps every hospital negotiating blind.',
    commercialImpact: 'Neutral bilaterally; systemically preserves the information asymmetry.',
    operationalImpact: 'Advisor access requires care.',
    burden: 1, complexity: 1, risk: 'Low',
    negotiationPriority: 2,
    evidence: ['Market-standard term'],
  },
  {
    id: 'AC-9.1', contract: 'AusCare', ref: 'cl. 9.1', title: 'Transfer absorbs extended recovery',
    category: 'Clinical',
    excerpt: '…No additional amount is payable to the Hospital for extended recovery prior to transfer.',
    plain: 'If a patient can\'t be discharged and must be transferred, the extra hours of care are unpaid.',
    commercialImpact: 'Small direct cost; Board already absorbs by policy (DR-2025-06).',
    operationalImpact: 'Clinical pathway + documentation requirements.',
    burden: 2, complexity: 2, risk: 'Low',
    negotiationPriority: 3,
    valuation: {
      method: 'Automated (PAS + revenue data)', annualValue: 4_000,
      confidence: 'High',
      basis: '~16 extended-recovery episodes/yr × measured marginal staffing cost.',
      overrides: [],
    },
    evidence: ['PAS extended-recovery episodes FY26'],
  },
  // ---------------- Federation (2025) — the benchmark contract ----------------
  {
    id: 'FED-9.1', contract: 'Federation', ref: 'cl. 9.1', title: 'Full-CPI indexation, no carve-out',
    category: 'Financial',
    excerpt: '…adjusted by the full percentage movement in CPI… There is no discretionary reduction mechanism.',
    plain: 'CPI means CPI. The benchmark clause the AusCare renewal is targeting.',
    commercialImpact: 'Revenue certainty; the portfolio\'s strongest indexation.',
    operationalImpact: 'None.',
    burden: 1, complexity: 1, risk: 'Low', negotiationPriority: 1,
    evidence: ['FY26 indexation applied at 3.4% + loading'],
  },
  {
    id: 'FED-5.1', contract: 'Federation', ref: 'cl. 5.1', title: 'Mutual-consent re-banding with expert referee',
    category: 'Commercial',
    excerpt: 'Reassignment of a procedure between bands requires the written agreement of both parties… independent clinical coding expert whose determination binds…',
    plain: 'Nobody re-bands alone; deadlocks go to an independent expert.',
    commercialImpact: 'Protects rate integrity; the model position for AusCare cl. 8.4.',
    operationalImpact: 'None to date.',
    burden: 1, complexity: 2, risk: 'Low', negotiationPriority: 1,
    evidence: ['No unilateral re-bandings this term'],
  },
  {
    id: 'FED-4.3', contract: 'Federation', ref: 'cl. 4.3', title: '12-month recovery, disputes excluded',
    category: 'Payment',
    excerpt: '…may not recover an alleged overpayment by set-off more than 12 months after payment, and amounts under dispute are excluded…',
    plain: 'Half the AusCare look-back, and disputed money can\'t be seized mid-argument.',
    commercialImpact: 'Bounded audit exposure.',
    operationalImpact: 'Standard reconciliation.',
    burden: 2, complexity: 2, risk: 'Low', negotiationPriority: 2,
    evidence: ['Comparator for AusCare cl. 14.5 ask'],
  },
  {
    id: 'FED-7.1', contract: 'Federation', ref: 'cl. 7.1', title: 'Quality loading (+0.5%)',
    category: 'Quality',
    excerpt: 'Sustained top-quartile performance against Schedule B entitles the Hospital to a 0.5% quality loading…',
    plain: 'Excellence pays. Captured May 2026: +$17k/yr.',
    commercialImpact: 'Quality converted to revenue; template for the AusCare quality-incentive proposal.',
    operationalImpact: 'Quarterly KPI pack (shared with AusCare reporting).',
    burden: 2, complexity: 1, risk: 'Low', negotiationPriority: 1,
    valuation: {
      method: 'Automated (PAS + revenue data)', annualValue: 17_000,
      confidence: 'High',
      basis: 'Loading confirmed May 2026; applied to Federation base.',
      overrides: [],
    },
    evidence: ['Loading confirmation letter May 2026'],
  },
  {
    id: 'FED-6.1', contract: 'Federation', ref: 'cl. 6.1', title: 'Audit bounded to 12 months, disputes first',
    category: 'Audit',
    excerpt: '…limited to episodes within the preceding 12 months. Audit findings are subject to the dispute resolution process before any recovery action.',
    plain: 'Audits look back one year and can\'t take money until the argument is settled.',
    commercialImpact: 'Keeps audit season proportionate.',
    operationalImpact: 'Standard.',
    burden: 2, complexity: 1, risk: 'Low', negotiationPriority: 2,
    evidence: ['FY26 prostheses audit conducted within bounds'],
  },
  {
    id: 'FED-8.1', contract: 'Federation', ref: 'cl. 8.1', title: 'Symmetric 60-day termination',
    category: 'Termination',
    excerpt: 'Either party may terminate this Agreement without cause on 60 days’ written notice.',
    plain: 'Equal exits. The comparator that makes AusCare\'s 90/180 split untenable.',
    commercialImpact: 'Balanced leverage.',
    operationalImpact: 'None.',
    burden: 1, complexity: 1, risk: 'Low', negotiationPriority: 1,
    evidence: ['Comparator for AusCare cl. 19.1 ask'],
  },
]

// ------------------------------------------------------------- lever register
export interface Lever {
  id: string
  contract: Contract
  clauseRefs: string[]
  title: string
  issue: string
  why: string
  annualValue: number
  negotiationValue: number
  burden: Risk
  strategic: 1 | 2 | 3 | 4 | 5
  ease: 'Easy' | 'Moderate' | 'Hard'
  likelihoodPct: number
  recommended: string
  fallback: string
  dependencies: string[]
  evidence: string[]
  mustHave: boolean
  tradeable: boolean
  quickWin: boolean
}

export const levers: Lever[] = [
  {
    id: 'L1', contract: 'AusCare', clauseRefs: ['cl. 12.3'], title: 'Delete the indexation carve-out',
    issue: 'Discretionary below-CPI indexation', why: 'Already exercised once; compounds forever; poisons every rate outcome.',
    annualValue: 45_000, negotiationValue: 45_000, burden: 'Low', strategic: 5, ease: 'Moderate', likelihoodPct: 70,
    recommended: 'cl. 12.3 deleted; CPI floor retained; cap lifted to 4.25%.',
    fallback: 'Floor at 100% of CPI with cap unchanged (never a % -of-CPI floor — see fund’s trap wording).',
    dependencies: ['Condition of any multi-year term (L7)'], evidence: ['FY25 exercise', 'Federation cl. 9.1'],
    mustHave: true, tradeable: false, quickWin: false,
  },
  {
    id: 'L2', contract: 'AusCare', clauseRefs: ['cl. 8.4'], title: 'Consent-based re-banding + restore FY26 re-bandings',
    issue: 'Unilateral band reassignment', why: 'The largest measured leak ($108k/yr) and it recurs at the fund’s option.',
    annualValue: 108_000, negotiationValue: 108_000, burden: 'Medium', strategic: 5, ease: 'Hard', likelihoodPct: 55,
    recommended: 'Mutual consent; independent coding expert on deadlock; 4 ophthalmic groups restored to Band 2.',
    fallback: 'Fund committee first instance, jointly-appointed expert binding on appeal; 3 of 4 groups restored.',
    dependencies: ['Anchors the cataract rate ask (L3)'], evidence: ['Re-banding notices ×2', 'Episode modelling', 'Federation cl. 5.1'],
    mustHave: true, tradeable: false, quickWin: false,
  },
  {
    id: 'L3', contract: 'AusCare', clauseRefs: ['Schedule 1'], title: 'Cataract Band 2 re-price (+7%)',
    issue: 'Rate 7.2% under market on the highest-volume line', why: 'Largest single rate gap; fund’s own mechanics created it.',
    annualValue: 88_000, negotiationValue: 88_000, burden: 'Low', strategic: 5, ease: 'Moderate', likelihoodPct: 60,
    recommended: '+7.0% on Band 2 cataract from commencement.', fallback: '+5.5% with year-2 review against lens costs.',
    dependencies: ['Strengthened by L2 restoration evidence'], evidence: ['Benchmark medians (synthetic)', 'Volume-weighted gap model'],
    mustHave: false, tradeable: false, quickWin: false,
  },
  {
    id: 'L4', contract: 'AusCare', clauseRefs: ['cl. 14.5', 'cl. 14.2'], title: 'Rebalance recovery vs lodgement',
    issue: '24-month clawback vs 30-day lodgement', why: 'A 24:1 temporal asymmetry with direct audit-season exposure.',
    annualValue: 32_000, negotiationValue: 24_000, burden: 'Medium', strategic: 4, ease: 'Moderate', likelihoodPct: 65,
    recommended: 'Recovery 12 months, disputes excluded from set-off; lodgement 60 days with reasonable-delay carve-out.',
    fallback: 'Recovery 12 months, disputes excluded; lodgement stays 30 days (we offer 14-day lodgement as the give).',
    dependencies: [], evidence: ['Federation cl. 4.2–4.3', 'RI audit outcomes FY26'],
    mustHave: false, tradeable: false, quickWin: true,
  },
  {
    id: 'L5', contract: 'AusCare', clauseRefs: ['cl. 2.2'], title: 'Index the holdover',
    issue: 'Frozen rates during renewal drift', why: 'Removes the fund’s calendar weapon before it matters.',
    annualValue: 30_000, negotiationValue: 20_000, burden: 'Low', strategic: 4, ease: 'Easy', likelihoodPct: 75,
    recommended: 'Holdover indexed at CPI (Federation model).', fallback: 'Holdover indexed at 50% CPI, capped 6 months.',
    dependencies: ['Defuses timeline pressure on all other levers'], evidence: ['Federation cl. 2.2'],
    mustHave: false, tradeable: false, quickWin: true,
  },
  {
    id: 'L6', contract: 'AusCare', clauseRefs: ['cl. 17.3'], title: 'Quality loading for top-quartile KPIs',
    issue: 'Quality is all penalty, no incentive', why: 'Bayview already earns it on the Federation contract for the same data.',
    annualValue: 15_000, negotiationValue: 15_000, burden: 'Low', strategic: 3, ease: 'Moderate', likelihoodPct: 50,
    recommended: '+0.5% loading for sustained top-quartile Schedule 3 performance.', fallback: 'Year-1 review clause with agreed loading formula.',
    dependencies: ['Pairs naturally with fund’s quality narrative'], evidence: ['8 quarters top-quartile KPIs', 'Federation cl. 7.1'],
    mustHave: false, tradeable: true, quickWin: false,
  },
  {
    id: 'L7', contract: 'AusCare', clauseRefs: ['cl. 19.1'], title: 'Symmetric termination at 120 days',
    issue: '90/180 exit asymmetry', why: 'Cheap for the fund to concede; repairs BATNA credibility.',
    annualValue: 0, negotiationValue: 15_000, burden: 'Low', strategic: 3, ease: 'Easy', likelihoodPct: 80,
    recommended: 'Either party, 120 days.', fallback: 'Either party, 90 days.',
    dependencies: [], evidence: ['Federation cl. 8.1'], mustHave: false, tradeable: true, quickWin: true,
  },
  {
    id: 'L8', contract: 'AusCare', clauseRefs: ['cl. 10.2'], title: 'Lens-cost review mechanism',
    issue: 'IOL bundled without adjustment', why: 'Input-cost drift silently erodes the headline rate.',
    annualValue: 27_000, negotiationValue: 18_000, burden: 'Medium', strategic: 3, ease: 'Hard', likelihoodPct: 40,
    recommended: 'Annual lens-cost review adjusting the bundled component.', fallback: '"Good-faith review at year 1" with data-sharing commitment — park and revisit.',
    dependencies: ['Trade late for something small'], evidence: ['Consignment cost series'],
    mustHave: false, tradeable: true, quickWin: false,
  },
]

// ------------------------------------------------------------- packages (W2)
export interface LeverPackage {
  id: string
  name: string
  posture: string
  leverIds: string[]
  gives: string[]
  sequencing: string[]
  relationshipNote: string
}

export const packages: LeverPackage[] = [
  {
    id: 'P1', name: 'The evidence-led package', posture: 'Assertive re-band (recommended)',
    leverIds: ['L1', 'L2', 'L3', 'L4', 'L5'],
    gives: ['3-year term', 'Ortho growth volumes from FY28', '14-day claims lodgement'],
    sequencing: ['Open with L2+L3 as one evidence-backed story', 'L1 positioned as condition of term', 'L5 asked first — quick win that defuses the calendar', 'L4 lands in round two after audit-season data is tabled'],
    relationshipNote: 'Firm but built entirely on the fund’s own conduct — survivable for the account manager to sell internally.',
  },
  {
    id: 'P2', name: 'The balanced-reset package', posture: 'Collaborative uplift',
    leverIds: ['L1', 'L4', 'L5', 'L6', 'L7'],
    gives: ['3-year term with early-renewal option', 'Quarterly quality data pack', '14-day lodgement'],
    sequencing: ['Lead with mutual "modernisation" framing (L5, L7 quick wins)', 'L1 as the single substantive ask', 'L6 offered as joint quality story'],
    relationshipNote: 'Lower value, lowest friction; leaves the re-banding wound open for next cycle.',
  },
  {
    id: 'P3', name: 'The maximum-value package', posture: 'Full-spectrum',
    leverIds: ['L1', 'L2', 'L3', 'L4', 'L5', 'L6', 'L7', 'L8'],
    gives: ['5-year term', 'All growth volumes contracted', 'Full cost-transparency pack'],
    sequencing: ['Only viable with 6+ months of runway', 'Requires the restructure posture and executive sponsorship on the fund side'],
    relationshipNote: 'Highest value, highest escalation risk — hold as the walk-in position only if the fund opens aggressively.',
  },
]

export const leverById = (id: string) => levers.find((l) => l.id === id)!
export const fmtKv = (n: number) => (n >= 1000 ? `$${Math.round(n / 1000)}k` : n === 0 ? '—' : `$${n}`)
