/**
 * CANNED DEMO CONTENT — authored at build time. In the real product this is
 * generated by the model from the facility's data, the executed HPPA, and
 * public industry sources. All figures are synthetic and labelled in-app.
 */
export const positioningPaper = `
# Positioning paper — AusCare Health HPPA renewal

**Prepared for:** CEO, Bayview Day Surgery · **Negotiation:** AusCare agreement expiring 30 Nov 2026 · **Status:** confidential working draft

> **Summary.** You enter this negotiation stronger than the current agreement suggests. Your clinical record is a genuine asset, your volumes matter to AusCare's members in this catchment, and the fund's own economics show headroom. But three contract mechanisms — the indexation carve-out, unilateral re-banding, and the frozen holdover — have quietly cost you roughly **$214k over the current term**, and they will keep costing you under any rate outcome unless the *terms* are renegotiated alongside the *rates*. Aim for a rates-and-terms package, anchor above your target, and treat the second-tier fallback as a priced scenario rather than a threat.

## 1. Where you stand

### Financial exposure
AusCare is your second-largest payer: **$3.12m of annual revenue** across 1,690 episodes — 22% of facility revenue. Your facility EBITDA is $690k (4.9%), so the AusCare relationship is not optional: a bad outcome here is most of your margin. That is precisely why it deserves a prepared negotiation rather than an accepted renewal.

### Rate position vs market
Weighted by your volumes, your AusCare case payments sit **≈5.6% below the synthetic state medians** used in this demo:

| Service line | Volume share | Vs market | Annual impact |
|---|---|---|---|
| Cataract & IOL (Band 2) | 640 episodes | **−7.2%** | ≈ −$88k |
| Colonoscopy (Band 1) | 780 episodes | **−3.8%** | ≈ −$27k |
| Knee arthroscopy (Band 3) | 160 episodes | **−5.5%** | ≈ −$20k |
| Plastics (Bands 2–4) | 110 episodes | at market | — |

The cataract gap is the material one: it is your highest-margin line, your highest AusCare volume by revenue, and the line where the fund has *twice* used contractual mechanics (re-banding, the IOL bundle) to reduce effective rates without a negotiation.

### What the current terms have already cost you
- **cl. 12.3 (discretionary indexation):** FY25 indexation paid at 1.9% against CPI of 3.4%. On a $3.0m base, that is ≈ **$45k/yr, compounding** — the FY26 base is permanently lower.
- **cl. 8.4 (unilateral re-banding):** four ophthalmic item groups moved Band 2 → Band 1 in FY26 (YAG capsulotomy, minor glaucoma, pterygium, minor strabismus). ≈ 210 episodes × ≈ $1,127 rate difference ≈ **$237k/yr gross**; after case-mix substitution, realistically ≈ **$95–120k/yr**.
- **cl. 10.2 (IOL bundled):** lens cost inflation since 2023 has eroded the real cataract rate by ≈ **2.1%** on top of the headline gap.
- **cl. 2.2 (frozen holdover):** every month past 30 Nov without a new agreement costs ≈ **$8–11k** in forgone indexation — the *delay clock runs against you, not the fund*. Expect AusCare to be unhurried.

## 2. The counterparty

AusCare's own position (synthetic figures shaped on public-aggregate patterns):

- **Benefit ratio 83.1%** — below the industry's ~84–86% band: it returns less of each premium dollar as benefits than the average fund, while its management expenses run above the norm. There is headroom; rate discipline with providers is funding both margin and overhead.
- **Premium round:** AusCare took a **3.85% increase** into 2026 while paying you 1.9% indexation in FY25. This is a legitimate, documented talking point — *"your revenue line was indexed at twice the rate you indexed ours."*
- **Member exposure:** you are the shortest ophthalmic and endoscopy waitlist in the catchment. At second-tier default, AusCare's members face gap uncertainty at the area's highest-volume day facility — and AusCare already **over-indexes on Ombudsman complaints** relative to its size. Member abrasion is a cost the fund's contracting team has to weigh, even if it never says so.
- **Behavioural pattern:** expect a CPI-minus opening citing affordability, slow response cycles, and re-banding proposals presented as "classification tidy-ups". The pattern rewards a counterparty who arrives with modelling done and deadlines attached.

## 3. Your BATNA, priced

If no agreement is reached, second-tier default applies (≥85% of the fund's average contracted rate for comparable facilities). Modelled on your case mix:

| Scenario | AusCare revenue / yr | vs today |
|---|---|---|
| Current agreement | $3.12m | — |
| **Second-tier default** | **≈ $2.65m** | **−$470k (−15.1%)** |
| Second-tier + 20% volume leakage | ≈ $2.12m | −$1.0m |

Walking away is **survivable but expensive**: −$470k is most of your EBITDA, and some referrers will steer AusCare patients to contracted facilities. **Do not bluff a walk-away.** The honest strategic conclusion: your leverage is not the exit — it is (a) the fund's member-experience cost in this catchment, (b) your documented below-market position, and (c) your growth volumes (ortho pipeline ≈ 420 AusCare episodes/yr) which you can direct elsewhere *prospectively*.

## 4. Objectives — target / anchor / walk-away

| Element | Walk-away (min) | Target | Anchor (open) |
|---|---|---|---|
| Cataract Band 2 rate | +4.0% | **+7.0%** | +9.5% |
| Colonoscopy Band 1 | +2.0% | **+4.0%** | +5.5% |
| Arthroscopy Band 3 | +3.0% | **+5.5%** | +7.5% |
| Indexation | CPI floor, cap 4% | **CPI floor, no carve-out** | CPI + 0.5% |
| cl. 8.4 re-banding | Consent or expert referee | **Mutual consent required** | Delete; restore FY25 bandings |
| cl. 14.5 set-off | 12 months, disputes excluded | **6 months, disputes excluded** | Delete |
| Term & holdover | 3 yrs, holdover indexed | **3 yrs, holdover indexed at CPI** | 2 yrs + growth review |

Package value at target: ≈ **+$205–240k/yr** vs today. At walk-away minimums: ≈ +$120k/yr — still comfortably above the cost of the delay-risk it removes.

**Trade currency you hold** (give only against value): multi-year term certainty; ortho growth-volume commitment; quality-data reporting the fund can use for its own accreditation narratives; earlier claims lodgement.

## 5. Risk assessment

- **Fund goes slow (likely).** Mitigate: open early (this week), attach response dates to every letter, and put the holdover-indexation fix at the front of the terms ask — it defuses the delay weapon.
- **Fund offers rates but refuses terms (likely).** A +4% headline with cl. 12.3 intact is worth less than +2.5% with it deleted. Hold the terms line; the paper's modelling gives you the numbers to show why.
- **Fund proposes re-banding "modernisation" (possible).** Treat any Schedule 1 reclassification as a rate change and price it before responding.
- **Escalation to termination posture (unlikely).** You have not threatened exit; the fund gains little from a public dispute with a high-quality day facility while sector contracting is under political attention. If it arises, the second-tier model above is your prepared, unemotional answer.

## 6. Recommended next step

Proceed to **Strategy** and select a posture. On this analysis the evidence best supports **Assertive re-band** — the cataract/ophthalmic position is the largest recoverable value and the fund's own mechanics created it — but all three postures below are internally consistent with this paper, and the choice is yours.

---
*Canned demonstration output on synthetic data (Bayview Day Surgery and AusCare Health are fictional). In production this paper is generated from the facility's actual data and the executed HPPA, with every market figure cited to its public source. Decision support — not legal or financial advice.*
`
